name: Build TurboCore.exe

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Descarregar o código
        uses: actions/checkout@v4

      - name: Instalar .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Compilar TurboCore.exe
        run: dotnet publish TurboCore/TurboCore.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o publish

      - name: Disponibilizar o .exe para download
        uses: actions/upload-artifact@v4
        with:
          name: TurboCore
          path: publish/TurboCore.exe
